### ISSUE TITLE
Design of Activation and Follow-up Emails

### ISSUE THREAD

**Issue by cngo-github** [Woobo/Design---Graphic#1]
@Woobo/design Please look over the design of the below emails. This design needs to be finalized before launch.

<img width="971" alt="screen shot 2017-09-16 at 1 55 24 pm" src="https://user-images.githubusercontent.com/5151593/30514626-f44b9182-9ae6-11e7-918b-cad5244bd6e1.png">
<img width="538" alt="screen shot 2017-09-16 at 2 03 38 pm" src="https://user-images.githubusercontent.com/5151593/30514694-220b2942-9ae8-11e7-83f6-9a02443295e4.png">

**Comment by cngo-github** [comment]
Moved to Issue https://github.com/Woobo/Design---UI/issues/3.

**Comment by guoshen414** [comment]
got it




GUO SHENCofounder & Designer

917-952 7880
198 River St. Cambridge, MA 02139
*www.woobo.io*     <http://www.woobo.io/>
<https://www.facebook.com/AskWoobo/>    <https://twitter.com/askwoobo>
<https://www.instagram.com/askwoobo/>
